EN-4086: Need to set the ID on TermBo's TermSpecificationBo, or else a new ID will be incorrectly assigned when the TermBo is persisted.
This fixes an issue where creating a new Agenda containing Question
terms (and possibly others) causes the Agenda Editor maint doc to go
into exception routing with this error:

java.sql.SQLIntegrityConstraintViolationException: ORA-01400: cannot
insert NULL into ("KR"."KRMS_TERM_SPEC_T"."NM")